---
monitoring_stack_dir: /opt/crawler-monitoring
monitoring_grafana_port: 3000
monitoring_prometheus_port: 9090
monitoring_loki_port: 3100
monitoring_cadvisor_port: 8081
monitoring_node_exporter_port: 9100

monitoring_grafana_admin_user: admin
monitoring_grafana_admin_password: admin123!
monitoring_grafana_default_timezone: browser

monitoring_webapp_metrics_host: host.docker.internal
monitoring_webapp_metrics_port: "{{ crawler_web_port | default(8080) }}"
